### ISSUE TITLE
Does it work if the key has dot character ?

### ISSUE THREAD

**Issue by saurabhmahajan0077** [75lb/sort-array#5]
So I have a JSON in the format 

`{"homepage_card.title":{"type":"StructuredText","value":[{"type":"heading1","text":"Test Card","spans":[]}]},"homepage_card.type":{"type":"Select","value":"default"},"homepage_card.sequence":{"type":"Number","value":4},"homepage_card.description":{"type":"StructuredText","value":[{"type":"paragraph","text":"This is some description","spans":[]}]},"homepage_card.background_image":{"type":"Image","value":{"main":{"dimensions":{"width":960,"height":800},"alt":null,"copyright":null,"url":"https://wroomdev.s3.amazonaws.com/tutoblanktemplate%2F97109f41-140e-4dc9-a2c8-96fb10f14051_star.gif"},"views":{}}},"homepage_card.label":{"type":"Text","value":"Label"},"homepage_card.rotating_cards":{"type":"Group","value":[{}]}}`

where the keys have a dot.

It did not seem to work for this case when I was trying to sort `homepage_card.sequence.value`

**Comment by 75lb** [comment]
no, that doesn't work and we have a problem because the expression `homepage_card.sequence.value` is ambiguous. Does it mean we want to search the `homepage_card` field for the `sequence.value` expression? Or does it mean we want to search the `homepage_card.sequence` field for the `value` expression? 

How to fix? Introduce an escape character to the search expression, e.g. `homepage_card\\.sequence.value`?

**Comment by 75lb** [comment]
searching by deep object values (using computed fields) added and released in v3.0.0
